openapi: 3.0.3
info:
  title: CMS Service
  version: 1.0.11
servers:
  - url: http://localhost:9765

paths:
  /retrieve_logs:
    get:
      tags:
      - Super Administrator
      summary: Retrieve Logs
      description: |
        By passing in the appropriate options, you can search for
        available logs in the system
      operationId: retrieveLogs
      parameters:
      - name: time
        in: query
        description: Time for which logs are retrieved
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: ABHA_ID
        in: query
        description: retrieve logs by hospital ID
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
        "400":
          description: bad input parameter
  /add_hospital_instance:
    post:
      tags:
      - Super Administrator
      summary: adds a hospital
      operationId: addHospital
      requestBody:
        description: Adds an item to the system
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hospitals'
        required: true
      responses:
        "201":
          description: Hospital created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
  /add_category:
    post:
      tags:
      - Super Administrator
      summary: Add Medical Category
      description: Adds Category
      operationId: addCategory
      requestBody:
        description: Create a new patient in a hospital
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
        required: true
      responses:
        "201":
          description: item added
        "400":
          description: invalid input, object invalid
  /login:
    post:
      tags:
        - login
      summary: Login the doctors and patients to the CMS
      description: Based on the username and password we will login doctor and patient
      operationId: loginUsers
      requestBody:
        description: Login the doctors and patients to the CMS
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'          
        '404':
          description: Credentials not found

  /doctor/request-consent:
    post:
      tags:
        - Doctor request consent
      summary: Doctor request consent from patients
      description: Doctor can create a custom consent artifact and request consent
      operationId: sendConsentRequest
      requestBody:
        description: send consent request based on patient ABHA ID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestConsent'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/consentResponse'          
        '405':
          description: Invalid input
  /doctor/get-consent:
    get:
      tags:
        - Doctor request consent
      summary: Doctor retreives the consents 
      description: Doctor wants to retreive all the consents that he has made.
      operationId: getConsentRequest
      parameters:
        - name: NPI_ID
          in: query
          description: NPI ID to retreive consents that he has requested
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentGetResponse'          
        '405':
          description: Invalid input
          
  /validator:
    post:
      tags:
        - validate
      summary: checks if consent is still valid or revoked or dosent exist
      description: Mediator service will use this API to validate if it should send data to a doctor upon request
      operationId: validateDataTransfer
      requestBody:
        description: send consent request based on patient ABHA ID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validatorRequestBody'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validatorResponse'          
        '405':
          description: Invalid input

components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: string
          example: "email@example.com"
        password:
          type: string
          format: password
          example: "*******"
    LoginResponse:
      type: object
      properties:
        user:
          type: string
          format: string
          enum:
          - "doctor"
          - "patient"
          example: "doctor"
          
    consentArtifactItems:
          type: object
          properties:
            category:
              type: string
              format: string
              example: "blood report"
            from:
              type: string
              format: date
              example: '2022-07-01'
            to:
              type: string
              format: date
              example: '2022-07-01'
            source_hospital:
              type: object
              properties:
                id:
                  type: string
                  format: string
                  example: "h2"
                name:
                  type: string
                  format: string
                  example: "hospital 2"
            dest_hospital:
              type: object
              properties:
                id:
                  type: string
                  format: string
                  example: "h1"
                name:
                  type: string
                  format: string
                  example: "hospital 1"
    requestConsent:
      type: object
      properties:
        ABHA_ID:
          type: string
          format: string
          example: "1986672626"
        consentArtifact:
          items:
            anyOf:
              - $ref: '#/components/schemas/consentArtifactItems'
    consentResponse:
      type: object
      properties:
        response:
          type: string
          format: string
          example: "consent requested successfully"
          
    validatorRequestBody:
      type: object
      properties:
        ABHA_ID:
          type: string
          format: string
          example: "201822222"
        Doctor_ID:
          type: string
          format: string
          example: "h1_d1"
        Consent_artifact_ID:
          type: string
          format: string
          example: "143"
          
    validatorResponse:
      type: object
      properties:
        validity:
          type: boolean
          format: boolean
          example: true
    Hospitals:
      type: object
      properties:
        H_ID:
          type: integer
          format: int64
        H_NAME:
          type: string
    Categories:
      type: object
      properties:
        Category_id:
          type: integer
          format: int64
        Category_name:
          type: string
    Logs:
      type: object
      properties:
        ABHA_ID:
          type: integer
          format: int64
        NPI_ID:
          type: integer
          format: int64
        timestamp:
          type: integer
          format: int64
        Artifact_ID:
          type: integer
          format: int64
        msg:
          type: string
    ConsentGetResponse:
      type: object
      properties:
        NPI_ID:
          type: integer
          example: 1
        consentArtifact:
          items:
            anyOf:
              - $ref: '#/components/schemas/consentArtifactItems'
      